stages:
  - deploy
deploy_production:
  stage: deploy
  script:
    - rsync -av * /var/www/html/www.jalyuzilar.uz/ --no-perms --no-owner --no-group
    - cd /var/www/html/www.jalyuzilar.uz/
    - docker-compose up --build -d
    - docker-compose exec -T frontend_medin ./init --env=Production --overwrite=All
    - docker-compose exec -T frontend_medin composer install
    - docker-compose exec -T frontend_medin ./yii migrate --interactive=0
  environment:
    name: production
    url: http://jalyuzilar.uz/
  only:
    - master
